/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/react-app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material 3 — Águas da Fonte (light)
        "outline-variant": "#c3c5d7",
        "surface-tint": "#1353d8",
        "surface-bright": "#faf8ff",
        "tertiary-container": "#b62f00",
        "inverse-primary": "#b5c4ff",
        "on-primary-container": "#d4dcff",
        "inverse-surface": "#2e3039",
        "secondary": "#006c4b",
        "error": "#ba1a1a",
        "tertiary": "#8c2200",
        "secondary-fixed-dim": "#7ad9ad",
        "on-error": "#ffffff",
        "on-primary-fixed": "#00174d",
        "surface-container-high": "#e7e7f3",
        "secondary-container": "#96f6c8",
        "outline": "#737686",
        "surface-container": "#ededf8",
        "primary-fixed": "#dbe1ff",
        "on-secondary-container": "#00734f",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#3b0900",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#872100",
        "on-secondary-fixed": "#002114",
        "on-secondary": "#ffffff",
        "primary-container": "#1a56db",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f0f0fb",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e2e1ed",
        "surface": "#faf8ff",
        "on-tertiary-container": "#ffd3c8",
        "primary-fixed-dim": "#b5c4ff",
        "tertiary-fixed-dim": "#ffb5a0",
        "surface-variant": "#e2e1ed",
        "on-background": "#191b23",
        "surface-container-low": "#f3f3fe",
        "on-surface": "#191b23",
        "tertiary-fixed": "#ffdbd1",
        "background": "#F8F9FA",
        "primary": "#003fb1",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434654",
        "surface-dim": "#d9d9e4",
        "secondary-fixed": "#96f6c8",
        "on-secondary-fixed-variant": "#005137",
        "on-primary-fixed-variant": "#003dab",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        card: "12px",
        btn: "8px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        margin: "32px",
        base: "4px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "Avenir", "Helvetica", "Arial", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "h2": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "h3": ["20px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "button": ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
        "h1": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        "ambient-1": "0px 4px 12px rgba(0, 0, 0, 0.03)",
        "ambient-2": "0px 8px 24px rgba(0, 0, 0, 0.06)",
        "ambient-3": "0px 12px 32px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
};
